name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRGIT_USER: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Generate Version 🧮
        run: ./gradlew calculateVersion -PexportToGithub=true --scan
      - name: Build 🔨
        run: ./gradlew release check -Pversion=${{ env.TAGGER_VERSION }} --scan
